generator:
  nlabels: 100
  conditioning: embedding
discriminator:
  nlabels: 100
  conditioning: mask
clusterer:
  name: selfcondgan
  kwargs: 
    k_value: 100
inherit_from: configs/cifar/default.yaml
training:
  out_dir: output/cifar/selfcondgan
  recluster_every: 25000